[phases.setup]
nixPkgs = ["php82Extensions.intl", "nodejs_20"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[start]
cmd = "bash scripts/railway-start.sh"
